# Title and subheading for your site. Used on the home page and in page
# titles.
#
title: "Gerhard Lazu"
subtitle: "developer, of all sorts"

# If you want to set the description or keywords meta tags on your site's
# home page, do it here.
#
description: "Former TXP & PHP developer, now rocking it with Ruby & JS with ever-increasing TDD"
keywords: "gerhard lazu, ruby, rails, javascript, jquery, php, txp"

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
  name: Gerhard Lazu
  uri: http://gerhardlazu.com
  email: mail@gerhardlazu.com

# You can stick with the default look and feel, or use a theme. Themes are
# easy to create or install, and live inside the themes directory. You
# can also use scripts/theme to install them.
#
theme: postal3

# If you want to use the Disqus service (http://disqus.com) to display
# comments on your site, register a Disqus account and then specify your
# site's short name here. A comment form will automatically be added to
# the bottom of your pages.
#
disqus_short_name: gerhardlazu

# The remaining configuration settings are set separately in development
# (i.e. when running on your local workstation) and production (when running
# on your live server).
#
# content - the root directory where nesta will look for your article files.
# Should contain "articles", "categories" and "attachments" subdirectories
# that contain your actual content.
#
# google_analytics_code - set this if you want Google Analytics to track
# traffic on your site. Probably best not to set it in development mode.
#
development:
  cache: false
  content: content

production:
  cache: false
  content: content
  google_analytics_code: "UA-106574-1"
