postal3: git://github.com/gma/nesta-theme-postal3.git
penguinclassics: git://github.com/sshingler/nesta-theme-penguinclassics.git
schmitzelburger: git://github.com/schmitzelburger/nesta-theme-schmitzelburger.git